export default {
  SAVE_USER: "SAVE_USER",
  GET_COUNTRIES: "GET_COUNTRIES_ACTION",
  GET_COUNTRIES_SUCCESS: "GET_COUNTRIES_SUCCESS",
  GET_COUNTRIES_PENDING: "GET_COUNTRIES_PENDING",
  SAVE_IMAGES_ACTION: "SAVE_IMAGES_ACTION"
};
